// normalizes x ∈ { subscript,superscript } to normal ascii so the lexer doesn't get too complicated

pub fn subscript(c: char) -> Option<char> {
    match c {
        '₀' => Some('0'),
        '₁' => Some('1'),
        '₂' => Some('2'),
        '₃' => Some('3'),
        '₄' => Some('4'),
        '₅' => Some('5'),
        '₆' => Some('6'),
        '₇' => Some('7'),
        '₈' => Some('8'),
        '₉' => Some('9'),
        '₊' => Some('+'),
        '₋' => Some('-'),
        '₌' => Some('='),
        '₍' => Some('('),
        '₎' => Some(')'),
        'ₐ' => Some('a'),
        'ₑ' => Some('e'),
        'ₕ' => Some('h'),
        'ᵢ' => Some('i'),
        'ⱼ' => Some('j'),
        'ₖ' => Some('k'),
        'ₗ' => Some('l'),
        'ₘ' => Some('m'),
        'ₙ' => Some('n'),
        'ₒ' => Some('o'),
        'ₚ' => Some('p'),
        'ᵣ' => Some('r'),
        'ₛ' => Some('s'),
        'ₜ' => Some('t'),
        'ᵤ' => Some('u'),
        'ᵥ' => Some('v'),
        'ₓ' => Some('x'),
        _ => None,
    }
}

pub fn superscript(c: char) -> Option<char> {
    match c {
        '⁰' => Some('0'),
        '¹' => Some('1'),
        '²' => Some('2'),
        '³' => Some('3'),
        '⁴' => Some('4'),
        '⁵' => Some('5'),
        '⁶' => Some('6'),
        '⁷' => Some('7'),
        '⁸' => Some('8'),
        '⁹' => Some('9'),
        '⁺' => Some('+'),
        '⁻' => Some('-'),
        '⁼' => Some('='),
        '⁽' => Some('('),
        '⁾' => Some(')'),
        'ᵃ' => Some('a'),
        'ᵇ' => Some('b'),
        'ᶜ' => Some('c'),
        'ᵈ' => Some('d'),
        'ᵉ' => Some('e'),
        'ᶠ' => Some('f'),
        'ᵍ' => Some('g'),
        'ʰ' => Some('h'),
        'ⁱ' => Some('i'),
        'ʲ' => Some('j'),
        'ᵏ' => Some('k'),
        'ˡ' => Some('l'),
        'ᵐ' => Some('m'),
        'ⁿ' => Some('n'),
        'ᵒ' => Some('o'),
        'ᵖ' => Some('p'),
        'ʳ' => Some('r'),
        'ˢ' => Some('s'),
        'ᵗ' => Some('t'),
        'ᵘ' => Some('u'),
        'ᵛ' => Some('v'),
        'ʷ' => Some('w'),
        'ˣ' => Some('x'),
        'ʸ' => Some('y'),
        'ᶻ' => Some('z'),
        _ => None,
    }
}
